import {PRICING,SERVICES,STATUSES,money,dateLabel,calculate,newQuote,validateQuote,shareText} from './pricing.js';
import {createStorage} from './storage.js';
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let repository;let quote=newQuote(),view='builder',storageError='',search='',activeSummary;
try{repository=createStorage(localStorage);const saved=repository.loadActive();if(saved){calculate(saved);quote=saved;}}catch{storageError='Draft recovery is unavailable. Keep this tab open and export important quotes.';}
const root=$('#app');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function persist(){quote.updatedAt=new Date().toISOString();try{repository.saveActive(quote);storageError='';}catch{storageError='Could not save on this device. Keep this tab open; export a copy of your quotation.';}const label=$('#save-state');if(label)label.textContent=storageError||'Draft saved on this device';}
function history(){try{return repository.loadHistory();}catch{toast('Saved quotations could not be read. Your current draft is safe in this tab.');return [];}}
function save(notify=true){const problem=validateQuote(quote);if(problem){toast(problem);return false;}try{persist();repository.saveQuote(quote);if(notify)toast('Quotation saved to history on this device.');return true;}catch{toast('Could not save. Your quotation is still here. Try exporting or saving a PDF.');return false;}}
function badge(){return `<span class="brand" aria-label="Apex Media">apex<span>medias.in</span></span>`;}
function header(){return `<header class="topbar"><a class="brand-link" href="#" aria-label="Apex Media quotation builder" data-action="builder">${badge()}</a><span class="workspace-label">QUOTATION STUDIO</span><nav aria-label="Main navigation"><button class="nav-button ${view==='builder'?'active':''}" data-action="builder">Builder</button><button class="nav-button ${view==='history'?'active':''}" data-action="history">History</button></nav><button class="button small dark" data-action="new" aria-label="New quotation">＋ <span>New quote</span></button></header>`;}
function clientFields(){return `<section class="panel client-panel"><div class="section-title"><span class="step-number">1</span><h2>The client</h2><span class="section-note">Start with a name</span></div><label for="business">Business / shop name <span class="required">*</span></label><input id="business" data-client="business" placeholder="e.g. The Chai Cartel" autocomplete="organization" maxlength="120" value="${esc(quote.client.business)}"><details ${Object.entries(quote.client).some(([k,v])=>k!=='business'&&v)?'open':''}><summary>Contact details & notes <span>Optional</span></summary><div class="contact-grid">${[['contact','Contact person','text','name'],['phone','Phone number','tel','tel'],['email','Email address','email','email']].map(([id,label,type,autocomplete])=>`<div><label for="${id}">${label}</label><input id="${id}" data-client="${id}" type="${type}" autocomplete="${autocomplete}" maxlength="150" value="${esc(quote.client[id])}"></div>`).join('')}<div class="notes-field"><label for="notes">Internal notes <span class="muted">Not shown to clients</span></label><textarea id="notes" data-client="notes" rows="2" maxlength="2000" placeholder="Anything to remember for the follow-up">${esc(quote.client.notes)}</textarea></div></div></details></section>`;}
function locationFields(){return `<section class="panel"><div class="section-title"><span class="step-number">2</span><h2>Location</h2><span class="section-note">Sets your reel rate</span></div><div class="location-options" role="group" aria-label="Client location">${quote.pricing.locations.map(l=>`<button class="location ${quote.location===l.id?'selected':''}" data-location="${esc(l.id)}" aria-pressed="${quote.location===l.id}"><span><b>${esc(l.name)}</b><small>${money(l.reelPaise)} / reel</small></span><span class="selection-mark">${quote.location===l.id?'✓':'○'}</span></button>`).join('')}</div></section>`;}
function serviceConfig(s){const state=quote.services[s.id];if(!state.enabled)return '';if(s.kind==='quantity')return `<div class="service-config"><label for="value-${s.id}">Number of ${s.id}</label><div class="quantity-row"><div class="stepper"><button data-step="${s.id}" data-delta="-1" aria-label="Decrease ${s.id}" ${state.value===0?'disabled':''}>−</button><input id="value-${s.id}" data-value="${s.id}" type="number" inputmode="numeric" min="0" max="10000" step="1" value="${state.value}" aria-label="Number of ${s.id}"><button data-step="${s.id}" data-delta="1" aria-label="Increase ${s.id}" ${state.value===10000?'disabled':''}>＋</button></div><strong id="price-${s.id}">${money(state.value*(s.id==='reels'?quote.pricing.locations.find(l=>l.id===quote.location).reelPaise:quote.pricing.postPaise))}</strong></div></div>`;
 if(s.kind==='budget')return `<div class="service-config"><label for="value-meta">Advertising / media budget</label><div class="currency-input"><span>₹</span><input id="value-meta" data-value="meta" type="number" inputmode="decimal" min="0" max="10000000" step="0.01" value="${state.value}"></div><div class="budget-presets">${[5000,10000,25000].map(n=>`<button data-budget="${n}" class="chip">${money(n*100)}</button>`).join('')}</div><p class="fee-line">Management fee <b>${quote.pricing.metaBasisPoints/100}%</b><strong id="price-meta">${money(calculate(quote).items.find(i=>i.id==='meta').amountPaise)}</strong></p><p class="field-help">Media spend is separate from Apex Media service charges.</p></div>`;
 if(s.kind==='options')return `<fieldset class="service-config website-options"><legend class="sr-only">Website type</legend>${quote.pricing.websites.map(w=>`<label class="website-option"><input type="radio" name="website" data-website="${w.id}" ${state.value===w.id?'checked':''}><span><b>${esc(w.name)}</b><small>${esc(w.description)}</small></span><strong>${w.paise===null?'Custom Quote':money(w.paise)}</strong></label>`).join('')}</fieldset>`;
 return `<div class="custom-note">Pricing will be shared after reviewing the brand requirements and scope. <b>Custom Quote</b></div>`;}
function serviceFields(){return `<section class="services-section"><div class="section-title"><span class="step-number">3</span><h2>Build the scope</h2><span class="section-note">Choose what fits</span></div>${!quote.location?'<div class="location-reminder">Choose a location above to unlock services.</div>':''}<div class="services">${SERVICES.map(s=>`<article class="service ${quote.services[s.id].enabled?'enabled':''}"><label class="service-heading"><span class="service-symbol">${s.symbol}</span><span class="service-copy"><b>${s.name}</b><small>${s.description}</small></span><input type="checkbox" data-service="${s.id}" ${quote.services[s.id].enabled?'checked':''} ${!quote.location?'disabled':''} aria-label="Enable ${s.name}"><span class="toggle" aria-hidden="true"></span></label>${serviceConfig(s)}</article>`).join('')}</div></section>`;}
function itemsHtml(r){return r.items.map(i=>`<div class="quote-item"><div><b>${i.quantity!==undefined?i.quantity+' ':''}${esc(i.name)}</b><small>${esc(i.detail)}</small></div><strong class="${i.amountPaise===null?'custom-price':''}">${i.amountPaise===null?'Custom Quote':money(i.amountPaise)}</strong></div>`).join('');}
function totalsHtml(r){return `<div class="totals"><div><span>Apex Media services</span><b>${r.hasFixed?money(r.servicePaise):'On consultation'}</b></div>${r.hasMedia?`<div><span>Advertising / media budget</span><b>${money(r.mediaPaise)}</b></div>`:''}<div class="grand-total"><span>${r.hasCustom?'Known project amount':'Project total'}</span><strong>${r.hasFixed?money(r.totalPaise):'Custom Quote'}</strong></div></div>${r.hasCustom?'<p class="custom-disclaimer">Additional custom service pricing is not included. Final project value may change after requirements are reviewed.</p>':''}`;}
function summary(){const r=calculate(quote);activeSummary=r;return `<div class="summary-top"><span class="eyebrow">YOUR QUOTATION</span><span class="live-badge">Live</span></div><h2>${esc(quote.client.business)||'Your next client'}</h2><p class="summary-location">${r.location||'Select a location'} <span>•</span> ${esc(quote.status)}</p>${r.items.length?itemsHtml(r)+totalsHtml(r):'<div class="empty-quote"><span>＋</span><h3>Good things start here.</h3><p>Select services to build your quotation.</p></div>'}<button class="button primary wide" data-action="present">Present to client <span>↗</span></button><div class="summary-actions"><button data-action="save" class="text-button">Save quotation</button><button data-action="review" class="text-button">Review details</button></div><p class="device-note" id="save-state">${storageError||'Draft saved on this device'}</p>`;}
function builder(){return `${header()}<main class="workspace"><div class="page-heading"><div><span class="eyebrow">FROM CONVERSATION TO COLLABORATION.</span><h1>BUILD. QUOTE. <span>GROW.</span></h1><p>A clear scope. A confident next move.</p></div><span class="edition">SALES WORKSPACE <b>01 / QUOTE</b></span></div><div class="builder-grid"><div class="builder-fields">${clientFields()}${locationFields()}${serviceFields()}</div><aside class="quote-summary" id="quote-summary" aria-label="Live quotation summary">${summary()}</aside></div><footer class="workspace-footer"><span>Apex Media · Made for the next conversation.</span><span>apexmedias.in</span></footer></main><div class="mobile-bar"><div id="mobile-total">${mobileTotal()}</div><button class="button primary" data-action="review">Review quote ↗</button></div>`;}
function mobileTotal(){const r=calculate(quote);return `<small>${r.items.length?r.hasCustom?'Known amount · custom extra':'Project total':'Your quotation'}</small><b>${r.items.length?r.hasFixed?money(r.totalPaise):'Custom Quote':'Select services'}</b>`;}
function proposal(){const r=calculate(quote);return `<div class="presentation"><div class="presentation-toolbar"><button class="button secondary" data-action="builder">← Edit quote</button><div><button class="button secondary" data-action="share">Share</button><button class="button dark" data-action="pdf">Save PDF</button></div></div><main class="proposal"><div class="proposal-top">${badge()}<div><span class="eyebrow">PREPARED WITH PURPOSE</span><p>${esc(quote.id)}<br>${dateLabel(quote.createdAt)}</p></div></div><div class="proposal-title"><span class="eyebrow">A PROPOSAL FOR WHAT’S NEXT</span><h1>YOUR BRAND.<br>YOUR NEXT<br><em>BIG MOVE.</em></h1></div><div class="prepared-for"><div><span class="eyebrow">PREPARED FOR</span><h2>${esc(quote.client.business)}</h2>${quote.client.contact?`<p>${esc(quote.client.contact)}</p>`:''}${quote.client.phone||quote.client.email?`<p>${esc([quote.client.phone,quote.client.email].filter(Boolean).join(' · '))}</p>`:''}</div><div><span class="eyebrow">LOCATION</span><p>${esc(r.location)}</p></div></div><section class="proposal-services"><div class="proposal-section-heading"><h2>Your scope of work</h2><span>${r.items.length} selected service${r.items.length===1?'':'s'}</span></div>${itemsHtml(r)}</section><section class="proposal-investment"><div><span class="eyebrow">YOUR INVESTMENT</span><h2>A clear scope.<br>A confident next step.</h2></div><div>${totalsHtml(r)}</div></section><p class="proposal-terms">Pricing shown is based on the selected scope of work. Advertising/media budgets are separate from Apex Media service charges. Services marked as custom quotation require further requirement analysis before final pricing is confirmed.</p><footer class="proposal-footer"><b>Let’s make your next move count.</b><a href="https://apexmedias.in" target="_blank" rel="noopener">apexmedias.in ↗</a></footer></main><div class="presentation-bottom"><button class="button secondary" data-action="save">Save quotation</button><button class="button primary" data-action="whatsapp">Share on WhatsApp ↗</button></div></div>`;}
function historyCards(){const all=history().filter(q=>[q.client.business,q.client.phone,q.id].some(v=>v.toLowerCase().includes(search.toLowerCase())));return all.length?all.map(q=>{const r=calculate(q);return `<button class="history-card" data-open="${q.id}"><div><span class="status">${esc(q.status)}</span><h2>${esc(q.client.business)}</h2><p>${esc(r.location)} · ${dateLabel(q.createdAt)}</p><small>${esc(q.id)}</small></div><div><strong>${r.hasFixed?money(r.totalPaise):'Custom Quote'}</strong>${r.hasCustom?'<small>Custom pricing additional</small>':''}<span class="open-quote">Open quotation ↗</span></div></button>`;}).join(''):`<div class="history-empty"><h2>${search?'No matching quotations':'Your next win starts with a quote.'}</h2><p>${search?'Try a business name, phone number or quotation ID.':'Saved quotations appear here, on this browser and device.'}</p>${!search?'<button class="button primary" data-action="builder">Build a quotation ↗</button>':''}</div>`;}
function historyView(){return `${header()}<main class="history-page"><div class="history-heading"><div><span class="eyebrow">KEEP THE CONVERSATION GOING</span><h1>Quotation history<span>.</span></h1><p>Saved on this browser. Export a backup to keep a copy.</p></div><button class="button secondary" data-action="export">Export backup</button></div><label class="sr-only" for="search">Search quotations</label><input class="search-input" id="search" type="search" placeholder="Search business, phone or quote ID" value="${esc(search)}"><div id="history-cards">${historyCards()}</div></main>`;}
function review(){const problem=validateQuote(quote);if(problem){toast(problem);if(!quote.client.business.trim())$('#business')?.focus();return;}view='review';render();}
function reviewView(){const r=calculate(quote);return `${header()}<main class="review-page"><button class="text-button" data-action="builder">← Back to builder</button><div class="review-heading"><span class="eyebrow">READY FOR THE CONVERSATION</span><h1>Review your quotation<span>.</span></h1><p>${esc(quote.id)} · ${dateLabel(quote.createdAt)}</p></div><div class="review-grid"><section class="panel"><span class="eyebrow">PREPARED FOR</span><h2>${esc(quote.client.business)}</h2><p>${esc(r.location)}</p>${itemsHtml(r)}${totalsHtml(r)}</section><section class="panel review-actions"><label for="status">Quotation status</label><select id="status">${STATUSES.map(s=>`<option ${quote.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="button primary wide" data-action="present">Present to client ↗</button><button class="button secondary wide" data-action="save">Save quotation</button><button class="button secondary wide" data-action="pdf">Save PDF</button><button class="button secondary wide" data-action="whatsapp">Share on WhatsApp</button><p class="field-help">History stays on this device. Saved quotes keep their original pricing and up to 20 previous revisions.</p></section></div></main>`;}
function render(){root.innerHTML=view==='presentation'?proposal():view==='history'?historyView():view==='review'?reviewView():builder();document.body.dataset.view=view;}
function updateSummary(){if($('#quote-summary'))$('#quote-summary').innerHTML=summary();if($('#mobile-total'))$('#mobile-total').innerHTML=mobileTotal();for(const i of calculate(quote).items){const p=$('#price-'+i.id);if(p)p.textContent=money(i.amountPaise);}for(const id of ['reels','posts']){const minus=$(`[data-step="${id}"][data-delta="-1"]`),plus=$(`[data-step="${id}"][data-delta="1"]`);if(minus)minus.disabled=quote.services[id].value===0;if(plus)plus.disabled=quote.services[id].value===10000;}persist();}
function present(){const problem=validateQuote(quote);if(problem){toast(problem);$('#business')?.focus();return false;}if(quote.status==='Draft')quote.status='Presented';persist();view='presentation';render();window.scrollTo(0,0);return true;}
async function action(name){if(name==='builder'||name==='history'){view=name;render();window.scrollTo(0,0);}else if(name==='review')review();else if(name==='present')present();else if(name==='save')save();else if(name==='new'){if(quote.client.business||Object.values(quote.services).some(s=>s.enabled))$('#confirm').showModal();else reset();}else if(name==='pdf'){if(present()){toast('Choose “Save as PDF” in the print dialog. The proposal has a dedicated print layout.');await new Promise(r=>setTimeout(r,150));window.print();}}else if(name==='whatsapp'){const problem=validateQuote(quote);if(problem)return toast(problem);window.open('https://wa.me/?text='+encodeURIComponent(shareText(quote)),'_blank','noopener,noreferrer');}else if(name==='share'){try{if(navigator.share)await navigator.share({title:`Apex Media • ${quote.client.business}`,text:shareText(quote)});else{await navigator.clipboard.writeText(shareText(quote));toast('Quotation summary copied.');}}catch(e){if(e.name!=='AbortError')toast('Sharing is unavailable. Use Share on WhatsApp or Save PDF.');}}else if(name==='export'){try{const blob=new Blob([repository.exportHistory()],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='apex-quotations-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch{toast('Backup could not be exported. Your draft is still available.');}}}
function reset(){quote=newQuote();persist();view='builder';render();window.scrollTo(0,0);}
$('#confirm').addEventListener('close',()=>{const result=$('#confirm').returnValue;if(result==='new'||(result==='save'&&save(false)))reset();});
root.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(t.dataset.action){e.preventDefault();action(t.dataset.action);}if(t.dataset.location){quote.location=t.dataset.location;persist();render();}if(t.dataset.step){const s=quote.services[t.dataset.step];s.value=Math.min(10000,Math.max(0,s.value+Number(t.dataset.delta)));persist();render();$(`[data-step="${t.dataset.step}"][data-delta="${t.dataset.delta}"]`)?.focus({preventScroll:true});}if(t.dataset.budget){quote.services.meta.value=Number(t.dataset.budget);persist();render();}if(t.dataset.open){const found=history().find(q=>q.id===t.dataset.open);if(found){if(quote.client.business||Object.values(quote.services).some(s=>s.enabled)){if(validateQuote(quote)){if(!window.confirm('Open this saved quotation? Your incomplete active draft will be replaced.'))return;}else if(!save(false))return;}quote=structuredClone(found);delete quote.revisions;persist();view='review';render();window.scrollTo(0,0);}}});
root.addEventListener('input',e=>{const t=e.target;if(t.dataset.client){quote.client[t.dataset.client]=t.value;updateSummary();}if(t.dataset.value){const id=t.dataset.value,max=id==='meta'?10000000:10000;const value=Number(t.value);if(t.value===''||!Number.isFinite(value)||value<0||value>max||(id!=='meta'&&!Number.isInteger(value))||(id==='meta'&&Math.abs(value*100-Math.round(value*100))>1e-6)){t.setCustomValidity(id==='meta'?'Enter a positive budget with at most two decimals (maximum ₹1,00,00,000).':'Enter a whole number from 0 to 10,000.');t.setAttribute('aria-invalid','true');return;}t.setCustomValidity('');t.removeAttribute('aria-invalid');quote.services[id].value=value;updateSummary();}if(t.id==='search'){search=t.value;$('#history-cards').innerHTML=historyCards();}});
root.addEventListener('focusout',e=>{if(e.target.dataset.value&&e.target.getAttribute('aria-invalid')){toast(e.target.validationMessage);e.target.value=quote.services[e.target.dataset.value].value;e.target.removeAttribute('aria-invalid');e.target.setCustomValidity('');}});
root.addEventListener('change',e=>{const t=e.target;if(t.dataset.service){quote.services[t.dataset.service].enabled=t.checked;persist();render();}if(t.dataset.website){quote.services.website.value=t.dataset.website;persist();render();}if(t.id==='status'){quote.status=t.value;persist();}});
window.addEventListener('beforeunload',e=>{if(storageError){e.preventDefault();e.returnValue='';}});
window.addEventListener('offline',()=>toast('You’re offline. Calculations and local saving still work.'));
render();if(storageError)toast(storageError);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_apex_quotation',description:'Read the active quotation and deterministic totals without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('No parameters accepted.');return {id:quote.id,client:quote.client.business,location:quote.location,...calculate(quote)};}})).catch(()=>{});}catch{}}
